name: build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: AWS Credential Setup
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
      #     aws-region: ${{ secrets.AWS_REGION }}
      - name: Build Web App
        run: npm install && npm run build
      # - name: Upload to S3 Bucket
      #   run: aws s3 sync ./build s3://${{ secrets.AWS_BUCKET_NAME }} --delete
      # Future step need to invalidate Cloudfront cache if/when AWS gets back to me :D
      # - name: Invalidate Cloudfront Cache
      #   run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }}
